version: 3.9

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./.models:/app/models
    command: uvicorn llm_advisor:app --host 0.0.0.0 --port 8000 --reload